apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T14:29:14Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4552"
  uid: 504db967-b877-498f-8ba2-68b2955878c6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.75.217
  clusterIPs:
  - 10.101.75.217
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31683
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
